export const ErrorCodes = {
  AI_PROVIDER_NOT_CONFIGURED: "AI_PROVIDER_NOT_CONFIGURED",
  AI_PROVIDER_AUTH_FAILED: "AI_PROVIDER_AUTH_FAILED",
  AI_PROVIDER_RATE_LIMITED: "AI_PROVIDER_RATE_LIMITED",
  AI_PROVIDER_TIMEOUT: "AI_PROVIDER_TIMEOUT",
  AI_PROVIDER_SERVER_ERROR: "AI_PROVIDER_SERVER_ERROR",
  AI_GENERATION_PARSE_FAILED: "AI_GENERATION_PARSE_FAILED",
  AI_STREAM_INTERRUPTED: "AI_STREAM_INTERRUPTED",
  AI_UNKNOWN: "AI_UNKNOWN",
  PROVIDER_RESOLUTION_FAILED: "PROVIDER_RESOLUTION_FAILED",
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
